from enum import Enum

class Marca_Bus(Enum):
    TOYOTA = "Toyota"
    FORD = "Ford"
    CHEVROLET = "Chevrolet"
    NISSAN = "Nissan"
    HONDA = "Honda"
    VOLKSWAGEN = "Volkswagen"
    MERCEDES_BENZ = "Mercedes-Benz"
    BMW = "BMW"
    AUDI = "Audi"
    HYUNDAI = "Hyundai"
    KIA = "Kia"
    MAZDA = "Mazda"
    SUBARU = "Subaru"
    JEEP = "Jeep"
    DODGE = "Dodge"
    RAM = "RAM"
    FIAT = "Fiat"
    SUZUKI = "Suzuki"
    MITSUBISHI = "Mitsubishi"
    RENAULT = "Renault"
    PEUGEOT = "Peugeot"
    CITROEN = "Citroën"
    SEAT = "SEAT"
    SKODA = "Škoda"
    TESLA = "Tesla"